authors = ["frank"]
name = "Juaparser"
uuid = "b992a966-e6ff-11e8-3fdb-4f129b99e5be"
version = "0.1.1"

[deps]
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
