authors = ["frank"]
name = "Juaparser"
uuid = "139258eb-c7dd-5548-aef6-6c8ebc1d244f"
version = "0.1.0"

[deps]
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
